twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    paths:
        'public/assets/images': images
        'public/assets/css': css

    globals:
        appname: "%app.name%"

when@test:
    twig:
        strict_variables: true
